### ISSUE TITLE
TS2451: Cannot redeclare block-scoped variable 'ngDevMode'

### ISSUE THREAD

**Issue by dcuenot** [rajan471/ngx-date-time-picker#1]
Hello,

This morning I did the update to angular 6, and I get this issue when I'm doing a `npm start`
`node_modules/ngx-date-time-picker/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.`

Do you an idea about what is going on?

Thanks for your help
Damien

**Comment by rajan471** [comment]
Hi Damien, I am looking into it and shall get back to you soon.

**Comment by thomaswmanion** [comment]
It's because Angular is a dep instead of a peer dep

**Comment by rajan471** [comment]
closing as is already answered.
